### PR TITLE
Avoid forcing the value for autoConnect

### PR DESCRIPTION
**Pull request by JlUgia**
If the first condition is met, autoConnect has the right to be both `true` or `false`.

### CODE REVIEW

**Comment by uKL** [comment]
I think it's still invalid. I think it should be Build.VERSION.SDK_INT < Build.VERSION_CODES.N && autoConnect

Dariusz, what do you think? The compatible should be applied to pre-made when autoConnect == true.

**Comment by dariuszseweryn** [comment]
I think that @JlUgia is right.
The condition seems right. If the `Build.VERSION.SDK_INT` is newer than or equal to Nougat then we're not using reflection. If the `autoConnect` is false we are also not using reflection.

**Comment by uKL** [comment]
That's right. I didn't see whole file on my mobile. I thought that reflection is in the `connectGattCompat`. I'd merge this one.

Shouldn't we have some tests for this logic?

**Comment by dariuszseweryn** [comment]
We could think about adding some tests but this one is ready for merge right away. Then we need to make a release of `1.1.1`

**Comment by uKL** [comment]
Dear Contributor,

similar to many open source projects we kindly request to sign our CLA if you'd like to contribute to our project. This license is for your protection as a Contributor as well as the protection of Polidea; it does not change your rights to use your own Contributions for any other purpose.

You can find a link here: https://cla-assistant.io/Polidea/RxAndroidBle

**Pull request merged**
