### PR TITLE
Fix exceptions stack trace so it include message instead of "null"

### PR DESCRIPTION
**Pull request by connected-jallen**

### CODE REVIEW

**Comment by dariuszseweryn** [comment]
Hello @connected-jallen!

Thank you for your pull request—it looks promising!
There are two things that make me think:
1. Now we loose the ability to call `(BleScanException| BleCannotSetCharacteristicNotificationException|BleDisconnectedException).toString()`. It would be a regression in terms of the funtionality
2. The exception message is usually a sentence that is easy to read by a human. The former implmenetation of `.toString()` gives all relevant information but does not make too much sense for a user that is not into BLE. Maybe the message could be just a sentence? i.e. having a `BleScanException` with a reason `LOCATION_SERVICES_DISABLED` could have a message like `Cannot start a scan due to Location Services being disabled`

What do you think? I look forward to discuss and merge your changes.

**Comment by Josh-Allen-ConnectedLab** [comment]
@dariuszseweryn Look at the source to Throwable and you will see that toString() returns message. You can probably get rid of your classname in createMessage() because it's already included by Throwable toString. Did you not notice that whenever you logged your exceptions using Timber or Log that it always said "BleScanException: null"? The way you had it coded means we need a special case for all of your exceptions to include toString() as well as stacktrace.

**Comment by dariuszseweryn** [comment]
That's true, we already have an opened issue for the messages #279 
I am thinking wether we should make the message more readable for non-tech savvy users. What do you think about it @connected-jallen ?
The class name indeed seems to be superfluous here.

**Comment by connected-jallen** [comment]
@dariuszseweryn I made the toString() messages cleaner.

**Comment by uKL** [comment]
It seems that this PR is a subset of #303, isn't it? I'll close this one in favor of #303. If you disagree please comment :) Thanks! Good job!

**Pull request closed without merging**
