### PR TITLE
Remove android-apt plugin

### PR DESCRIPTION
**Pull request by mapyo**
Thank you this repository!

android-apt is now available in the Android plugin.
ref. https://bitbucket.org/hvisser/android-apt/wiki/Migration

### CODE REVIEW

**Comment by dariuszseweryn** [comment]
Is the `annotationProcessor` in a stable version already?

**Comment by mzgreen** [comment]
Seems like it is. See this post from `android-apt` creator: https://www.littlerobots.nl/blog/Whats-next-for-android-apt/

**Comment by passsy** [comment]
It is stable since `com.android.tools.build:gradle:2.2.2'`. Furthermore the apt plugin will not work with the new 3.+ version of the android gradle plugin.

> android-apt plugin users: This behavior change currently does not affect the android-apt plugin. However, the plugin will not be compatible with future versions of the Android plugin for Gradle.

via [Use the annotation processor dependency configuration](https://developer.android.com/studio/build/gradle-plugin-3-0-0-migration.html#annotationProcessor_config)

**Comment by dariuszseweryn** [comment]
Great! 
@mapyo — could you merge the current top of the `master` branch so I could cleanly `Squash and merge` this PR?

**Comment by mapyo** [comment]
@dariuszseweryn 
Thank you for your review. I merged!

**Comment by dariuszseweryn** [comment]
Merged, thank you. 👍

**Pull request merged**
