### PR TITLE
Shaded Dagger dependency, fixes #342

### LINKED ISSUE #342: Can instantiate RxBleClient with last Dagger release
### Summary
I faced an issue yesterday with the new Dagger release (2.14.1). At the RxBleClient creation ( `RxBleClient.create(context);`) the app crash (with 2.13 and less it's ok) 

### Library version
`1.4.3`

#### Logs from the application running with setting 
```E/AndroidRuntime: FATAL EXCEPTION: main
                                                               Process: myapp.id, PID: 23473
                                                               java.lang.NoSuchMethodError: No static method injectMembers(Ldagger/MembersInjector;Ljava/lang/Object;)Ljava/lang/Object; in class Ldagger/internal/MembersInjectors; or its super classes (declaration of 'dagger.internal.MembersInjectors' appears in /data/app/myapp.id-2/base.apk:classe
at com.polidea.rxandroidble.RxBleAdapterStateObservable_Factory.get(RxBleAdapterStateObservable_Factory.java:28)
                                                       at com.polidea.rxandroidble.RxBleAdapterStateObservable_Factory.get(RxBleAdapterStateObservable_Factory.java:10)
                                                       at com.polidea.rxandroidble.RxBleClientImpl_Factory.get(RxBleClientImpl_Factory.java:104)
                                                       at com.polidea.rxandroidble.RxBleClientImpl_Factory.get(RxBleClientImpl_Factory.java:23)
                                                       at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
                                                       at com.polidea.rxandroidble.DaggerClientComponent.rxBleClient(DaggerClientComponent.java:419)
                                                       at com.polidea.rxandroidble.RxBleClient.create(RxBleClient.java:54)`

### PR DESCRIPTION
**Pull request by uKL**
Before:
```
Task :rxandroidble:countReleaseDexMethods 
Total methods in rxandroidble-release.aar: 2234 
Total fields in rxandroidble-release.aar:  1072 
Total classes in rxandroidble-release.aar:  513 
AAR size 374kB
```

After:
```
Task :rxandroidble:countReleaseDexMethods 
Total methods in rxandroidble-release.aar: 2180 
Total fields in rxandroidble-release.aar:  976 
Total classes in rxandroidble-release.aar:  510 
AAR size 363kB
```

Additionally, there is a JAR with 41kB with the shaded Dagger containing 187 methods.

### CODE REVIEW

**Comment by dariuszseweryn** [comment]
I am thinking if this should land in `1.5.0` or `1.4.4`... Thoughts?
On one hand the API does not change at all. On the other the we change the dependencies and someone could have used the transitive dagger dependency?

**Comment by uKL** [comment]
Having used a transitive dependency is an antipattern anyways. The same was with the rxandroid when we removed it.

In case of the dagger, there is a small chance that someone is using it this way due to the compiler dependency. It has to be added directly.

**Comment by dariuszseweryn** [comment]
Antipattern or not-still it can be something that breaks builds.
If we agree that it is just a bugfix then we should go with `1.4.4` but I think we already have some additional changes towards `1.5.0` there

**Comment by uKL** [comment]
Just to be safe we can go forward to 1.5.0 (we have changes related to operation timeout)

**Comment by dariuszseweryn** [comment]
I am just thinking whether we should temporarily revert operation timeout changes, release `1.4.4` with the shaded dagger and then go back to `1.5.0` with the operation timeout changes applied again

**Comment by uKL** [comment]
I'm gonna need them soon anyway so we can go with 1.5.0.

**Pull request merged**
