### PR TITLE
Fix dependency name for mockclient

### PR DESCRIPTION
**Pull request by nightscape**

### CODE REVIEW

**Comment by uKL** [comment]
Hey! :)

Could you follow up with explanation why did you decided to change it?

**Comment by nightscape** [comment]
Because the dependency as stated in the README does not seem to exist on the official Maven repos:
http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.polidea.rxandroidble%22
https://mvnrepository.com/artifact/com.polidea.rxandroidble
https://oss.sonatype.org/#nexus-search;quick~rxandroidble

An artifact called `mockclient` does exist in the repos and it seems to contain the code that is described in the README.

**Comment by dariuszseweryn** [comment]
I would prefer fixing the readme. ;)

**Comment by nightscape** [comment]
That's what I'm trying to do in this PR :confused: 
Now you really got me confused...

**Comment by dariuszseweryn** [comment]
Oh, my bad - excuse me. :)

**Comment by nightscape** [comment]
I was doubting my sanity already :smile:

**Comment by dariuszseweryn** [comment]
Sorry for that - my consciousness is not always top notch ;)  

Thanks for your PR.

**Pull request merged**
