### PR TITLE
[sample-kotlin] Rssi periodic and long write

### PR DESCRIPTION
**Pull request by lukaszkalnik**
Adds `RssiPeriodic` and `LongWrite` example Activities.

This PR builds on top of #540 . Please merge it afterwards.

### CODE REVIEW

**Comment by dariuszseweryn** [comment]
Aaaaaand — It is done! Thank you!

**Comment by lukaszkalnik** [comment]
Thank you for your reviews! It was fun doing this conversion :)
So now there are equivalent Java and Kotlin samples in the project 👍

**Comment by dariuszseweryn** [comment]
I am glad to hear that :)

One question: what styling you use for the kotlin files? I found my Android Studio default (or so I think) config formats the kotlin code differently

**Comment by lukaszkalnik** [comment]
https://github.com/grandcentrix/AndroidCodeStyle
It uses [official Kotlin code style][https://kotlinlang.org/docs/reference/coding-conventions.html].

**Comment by dariuszseweryn** [comment]
Yup, thanks for the info!

**Pull request merged**
